// The names of God and of Jesus for The Study's "Names of God" page, and
// for "Names of God in this reading" on a journal day (/api/bible/names
// spots them in a chapter by the Hebrew / Greek word behind the English).
//
// Verses quoted are from the Berean Standard Bible (public domain), the
// same text the rest of The Study shows. `say` is a plain-English
// respelling - the stressed part in capitals - read aloud by the speaker
// button.

export type NameGroup = "god" | "jesus";

export interface DivineName {
  id: string;
  group: NameGroup;
  name: string; // "El Shaddai"
  english: string; // "God Almighty"
  reads: string; // how English Bibles print it, e.g. "the LORD"
  original?: string; // Hebrew / Greek script
  lang: string; // "Hebrew", "Greek", "Aramaic"...
  translit?: string;
  say?: string; // "el shah-DYE"
  strongs?: string; // "H410 + H7706"
  meaning: string; // one line
  about: string[]; // paragraphs
  first: { ref: string; note: string };
  verses: string[];
}

export const NAMES: DivineName[] = [
  // ── Names of God ──────────────────────────────────────────────
  {
    id: "elohim",
    group: "god",
    name: "Elohim",
    english: "God",
    reads: "God",
    original: "אֱלֹהִים",
    lang: "Hebrew",
    say: "eh-lo-HEEM",
    strongs: "H430",
    meaning: "God - the mighty Creator, Judge and Ruler of all.",
    about: [
      "The very first name of God in the Bible: “In the beginning God created the heavens and the earth” (Genesis 1:1). Elohim is used about 2,600 times in the Old Testament.",
      "The word is plural in form but takes singular verbs when it means the one true God. It speaks of God's greatness and fullness - and many Christians see a first hint of the Trinity when God says, “Let Us make man in Our image” (Genesis 1:26).",
      "Elohim is the name of God as Creator and Judge of the whole earth - the God of all people, not only of Israel. The same word can mean false “gods”, or even human judges, so the passage around it shows which is meant.",
    ],
    first: { ref: "Genesis 1:1", note: "The first verse of the Bible." },
    verses: ["Genesis 1:1", "Genesis 1:26-27", "Deuteronomy 10:17", "Psalm 46:10"],
  },
  {
    id: "yahweh",
    group: "god",
    name: "Yahweh",
    english: "The LORD - I AM",
    reads: "the LORD",
    original: "יהוה",
    lang: "Hebrew",
    say: "YAH-weh",
    strongs: "H3068",
    meaning: "The self-existent, ever-present God who keeps His promises - God's own personal name.",
    about: [
      "God's personal, covenant name, written with four Hebrew letters (YHWH) and used nearly 7,000 times - more than any other name of God. Most English Bibles print it as LORD, in capital letters.",
      "God explained it to Moses at the burning bush: “I AM WHO I AM” (Exodus 3:14), and then, “This is My name forever, and this is how I am to be remembered in every generation” (Exodus 3:15). It comes from the Hebrew verb “to be” - He simply is. He depends on nothing, never changes, and is always present with His people.",
      "Out of reverence, Jewish readers stopped saying the name aloud and read “Adonai” (Lord) instead, so its exact sound was handed down uncertainly. “Jehovah” is an older English form, made by joining the letters YHWH to the vowels of Adonai. Whenever you see LORD in capitals, this is the name behind it.",
    ],
    first: { ref: "Genesis 2:4", note: "“the LORD God” - the story of creation, told again." },
    verses: ["Exodus 3:14-15", "Exodus 34:6-7", "Psalm 23:1", "Malachi 3:6"],
  },
  {
    id: "adonai",
    group: "god",
    name: "Adonai",
    english: "Lord, Master",
    reads: "Lord",
    original: "אֲדֹנָי",
    lang: "Hebrew",
    say: "ah-doh-NYE",
    strongs: "H136",
    meaning: "My Lord - the Master who rules, and to whom we belong.",
    about: [
      "Adonai means “Lord” or “Master”. It speaks of God's authority over us and of our place as His servants. English Bibles print it Lord - only the first letter a capital.",
      "Abram was the first to call God Adonai, when he asked, “O Lord GOD, what can You give me, since I remain childless?” (Genesis 15:2). When Adonai and YHWH stand together, Bibles print “Lord GOD” or “Sovereign LORD”.",
      "Because Jewish readers said Adonai in place of the holy name YHWH, its vowels were later written with YHWH - which is where the English form “Jehovah” came from.",
    ],
    first: { ref: "Genesis 15:2", note: "Abram calls God “Lord GOD” (Adonai YHWH)." },
    verses: ["Genesis 15:2", "Psalm 86:5", "Isaiah 6:1", "Daniel 9:19"],
  },
  {
    id: "el",
    group: "god",
    name: "El",
    english: "God, the Mighty One",
    reads: "God",
    original: "אֵל",
    lang: "Hebrew",
    say: "EL",
    strongs: "H410",
    meaning: "God - the strong and mighty One.",
    about: [
      "El is the oldest and shortest Hebrew word for God, meaning “mighty” or “strong”. It is often joined to another word that shows who God is: El Shaddai, El Elyon, El Roi, El Olam.",
      "It's inside many Bible names: Israel (“he struggles with God”), Daniel (“God is my judge”), Elijah (“my God is the LORD”), Immanuel (“God with us”) and Bethel (“house of God”).",
      "Isaiah calls the promised child “Mighty God” - El Gibbor (Isaiah 9:6).",
    ],
    first: { ref: "Genesis 14:18", note: "Melchizedek, priest of God Most High (El Elyon)." },
    verses: ["Genesis 33:20", "Deuteronomy 7:9", "Psalm 18:2", "Isaiah 9:6"],
  },
  {
    id: "el-shaddai",
    group: "god",
    name: "El Shaddai",
    english: "God Almighty",
    reads: "God Almighty, the Almighty",
    original: "אֵל שַׁדַּי",
    lang: "Hebrew",
    say: "el shah-DYE",
    strongs: "H410 + H7706",
    meaning: "God Almighty - the all-powerful God who is more than enough.",
    about: [
      "God showed Himself as El Shaddai to Abram at 99, still waiting for the son he'd been promised: “I am God Almighty. Walk before Me and be blameless” (Genesis 17:1). Then He changed his name to Abraham.",
      "Shaddai speaks of God's complete power - nothing is too hard for Him: “Is anything too difficult for the LORD?” (Genesis 18:14). Some link the word to a mountain (strength that cannot be moved), others to a mother's breast (the One who nourishes and provides). Both picture a God who is more than enough.",
      "Shaddai is used 48 times - 31 of them in Job, where it shows God's power over all creation. “He who dwells in the shelter of the Most High will abide in the shadow of the Almighty” (Psalm 91:1). In the New Testament the Greek word is Pantokrator, “the Almighty” (Revelation 1:8).",
    ],
    first: { ref: "Genesis 17:1", note: "God to Abram, aged 99." },
    verses: ["Genesis 17:1", "Genesis 28:3", "Genesis 35:11", "Exodus 6:3", "Psalm 91:1"],
  },
  {
    id: "el-elyon",
    group: "god",
    name: "El Elyon",
    english: "God Most High",
    reads: "God Most High, the Most High",
    original: "אֵל עֶלְיוֹן",
    lang: "Hebrew",
    say: "el el-YOHN",
    strongs: "H410 + H5945",
    meaning: "God Most High - above every power, every king and every so-called god.",
    about: [
      "First heard from Melchizedek, king of Salem and “priest of God Most High”, who brought out bread and wine and blessed Abram: “Blessed be Abram by God Most High, Creator of heaven and earth” (Genesis 14:19).",
      "Elyon means “highest”. God rules over every nation and power on earth - as Nebuchadnezzar learned, “the Most High rules over the kingdom of mankind and gives it to whom He wishes” (Daniel 4:32).",
      "In the New Testament the Greek is Hypsistos. Gabriel told Mary her son “will be great and will be called the Son of the Most High” (Luke 1:32).",
    ],
    first: { ref: "Genesis 14:18", note: "Melchizedek blesses Abram." },
    verses: ["Genesis 14:18-20", "Psalm 57:2", "Psalm 91:1", "Daniel 4:34", "Luke 1:32"],
  },
  {
    id: "el-roi",
    group: "god",
    name: "El Roi",
    english: "The God who sees me",
    reads: "the God who sees me",
    original: "אֵל רֳאִי",
    lang: "Hebrew",
    say: "el roh-EE",
    strongs: "H410 + H7210",
    meaning: "The God who sees me - who knows where I am and what I'm going through.",
    about: [
      "Hagar, an Egyptian slave, ran away into the desert from Sarai. The angel of the LORD found her by a spring of water and spoke to her by name.",
      "She is the only person in the Bible who gives God a name: “You are the God who sees me,” for she said, “Here I have seen the One who sees me!” (Genesis 16:13). The well was called Beer-lahai-roi - the well of the Living One who sees me.",
      "El Roi is a comfort for anyone who feels forgotten, overlooked or alone: God sees, knows and cares.",
    ],
    first: { ref: "Genesis 16:13", note: "Hagar in the desert." },
    verses: ["Genesis 16:13-14", "Psalm 33:18", "Psalm 139:1-3"],
  },
  {
    id: "el-olam",
    group: "god",
    name: "El Olam",
    english: "The Everlasting God",
    reads: "the Eternal God, the everlasting God",
    original: "אֵל עוֹלָם",
    lang: "Hebrew",
    say: "el oh-LAHM",
    strongs: "H410 + H5769",
    meaning: "The Everlasting God - no beginning, no end, and promises that never run out.",
    about: [
      "At Beersheba, Abraham “planted a tamarisk tree in Beersheba, and there he called upon the name of the LORD, the Eternal God” (Genesis 21:33).",
      "Olam means everlasting, beyond time. “From everlasting to everlasting You are God” (Psalm 90:2).",
      "Because He is everlasting He never wears out: “The LORD is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary” (Isaiah 40:28).",
    ],
    first: { ref: "Genesis 21:33", note: "Abraham at Beersheba." },
    verses: ["Genesis 21:33", "Psalm 90:2", "Isaiah 26:4", "Isaiah 40:28"],
  },
  {
    id: "yah",
    group: "god",
    name: "Yah",
    english: "The LORD (short form)",
    reads: "the LORD",
    original: "יָהּ",
    lang: "Hebrew",
    say: "YAH",
    strongs: "H3050",
    meaning: "A short, poetic form of Yahweh - the name inside “Hallelujah”.",
    about: [
      "Yah is used about 50 times, mostly in songs and psalms. Moses sang it after the Red Sea: “The LORD is my strength and my song, and He has become my salvation” (Exodus 15:2).",
      "It's in the word Hallelujah - “praise Yah”, praise the LORD - and in many names ending in -iah or -jah: Elijah (“my God is Yah”), Isaiah (“Yah saves”), Zechariah (“Yah remembers”).",
    ],
    first: { ref: "Exodus 15:2", note: "The song of Moses at the Red Sea." },
    verses: ["Exodus 15:2", "Psalm 68:4", "Psalm 150:6", "Isaiah 12:2"],
  },
  {
    id: "eloah",
    group: "god",
    name: "Eloah",
    english: "God",
    reads: "God",
    original: "אֱלוֹהַּ",
    lang: "Hebrew",
    say: "eh-LOH-ah",
    strongs: "H433",
    meaning: "God - the single form of Elohim, used most in Job.",
    about: [
      "Eloah is the singular form of Elohim, used about 57 times - more than 40 of them in the book of Job, as Job and his friends wrestle with who God is and why people suffer.",
      "“Every word of God is flawless; He is a shield to those who take refuge in Him” (Proverbs 30:5).",
    ],
    first: { ref: "Deuteronomy 32:15", note: "In the song of Moses." },
    verses: ["Job 19:26", "Psalm 18:31", "Proverbs 30:5"],
  },
  {
    id: "elah",
    group: "god",
    name: "Elah",
    english: "God (Aramaic)",
    reads: "God",
    original: "אֱלָהּ",
    lang: "Aramaic",
    say: "eh-LAH",
    strongs: "H426",
    meaning: "The Aramaic word for God, in the parts of Ezra and Daniel written in Aramaic.",
    about: [
      "Parts of Ezra and Daniel were written in Aramaic, the language of Babylon and Persia, and there God is Elah - often “the God of heaven”.",
      "Daniel told Nebuchadnezzar, “there is a God in heaven who reveals mysteries” (Daniel 2:28). After his madness the king himself spoke of “the Most High God” (Daniel 4:2).",
    ],
    first: { ref: "Ezra 4:24", note: "“the house of God in Jerusalem”" },
    verses: ["Ezra 5:11", "Daniel 2:28", "Daniel 4:2", "Daniel 6:26"],
  },
  {
    id: "yireh",
    group: "god",
    name: "Yahweh Yireh",
    english: "The LORD will provide",
    reads: "The LORD Will Provide (Jehovah Jireh)",
    original: "יְהוָה יִרְאֶה",
    lang: "Hebrew",
    say: "YAH-weh YEER-eh",
    strongs: "H3070",
    meaning: "The LORD will provide - He sees ahead, and sees to it.",
    about: [
      "On Mount Moriah God stopped Abraham from sacrificing Isaac and provided a ram caught in a thicket in his place. “And Abraham called that place The LORD Will Provide” (Genesis 22:14).",
      "Yireh literally means “will see”. On the way up the mountain Abraham had already told Isaac, “God Himself will provide the lamb for the burnt offering, my son” (Genesis 22:8).",
      "Solomon later built the temple on Mount Moriah (2 Chronicles 3:1), in Jerusalem - where God provided His own Son, “the Lamb of God, who takes away the sin of the world!” (John 1:29).",
    ],
    first: { ref: "Genesis 22:14", note: "The ram in the thicket." },
    verses: ["Genesis 22:8", "Genesis 22:14", "Romans 8:32", "Philippians 4:19"],
  },
  {
    id: "rapha",
    group: "god",
    name: "Yahweh Rapha",
    english: "The LORD who heals",
    reads: "the LORD who heals you",
    original: "יְהוָה רֹפְאֶךָ",
    lang: "Hebrew",
    say: "YAH-weh rah-FAH",
    strongs: "H7495",
    meaning: "The LORD who heals - bodies, hearts and nations.",
    about: [
      "Three days into the desert, Israel found only bitter water at Marah. God showed Moses a piece of wood, the water turned sweet, and He said, “For I am the LORD who heals you” (Exodus 15:26).",
      "Rapha means to heal, restore, make whole. “He heals the brokenhearted and binds up their wounds” (Psalm 147:3).",
      "Jesus showed this name in every healing - and above all at the cross: “and by His stripes we are healed” (Isaiah 53:5).",
    ],
    first: { ref: "Exodus 15:26", note: "The bitter water at Marah." },
    verses: ["Exodus 15:26", "Psalm 103:2-3", "Psalm 147:3", "Isaiah 53:5"],
  },
  {
    id: "nissi",
    group: "god",
    name: "Yahweh Nissi",
    english: "The LORD is my banner",
    reads: "The LORD Is My Banner",
    original: "יְהוָה נִסִּי",
    lang: "Hebrew",
    say: "YAH-weh NEE-see",
    strongs: "H3071",
    meaning: "The LORD is my banner - the victory is His, and we rally to Him.",
    about: [
      "When the Amalekites attacked Israel, Joshua fought in the valley while Moses held up his hands on the hill - and Israel won while his hands stayed raised. Afterwards “Moses built an altar and named it The LORD Is My Banner” (Exodus 17:15).",
      "A banner was a flag on a pole that soldiers gathered around in battle. The victory belongs to the LORD, and His people stand together under His name.",
      "Isaiah says the coming King, the Root of Jesse, “will stand as a banner for the peoples” (Isaiah 11:10).",
    ],
    first: { ref: "Exodus 17:15", note: "Victory over Amalek." },
    verses: ["Exodus 17:15", "Psalm 60:4", "Isaiah 11:10"],
  },
  {
    id: "mekoddishkem",
    group: "god",
    name: "Yahweh Mekoddishkem",
    english: "The LORD who makes you holy",
    reads: "the LORD who sanctifies you",
    original: "יְהוָה מְקַדִּשְׁכֶם",
    lang: "Hebrew",
    say: "YAH-weh meh-kah-DESH-kem",
    strongs: "H6942",
    meaning: "The LORD who sets you apart and makes you holy.",
    about: [
      "Given with the Sabbath, as a sign between God and His people for every generation, “so that you may know that I am the LORD who sanctifies you” (Exodus 31:13).",
      "To be holy is to be set apart for God. Israel couldn't make itself holy - God did it, and then called them to live like it (Leviticus 20:7-8).",
      "The same is true in Christ: “we have been sanctified through the sacrifice of the body of Jesus Christ once for all” (Hebrews 10:10).",
    ],
    first: { ref: "Exodus 31:13", note: "The Sabbath sign." },
    verses: ["Exodus 31:13", "Leviticus 20:8", "1 Thessalonians 5:23", "Hebrews 10:10"],
  },
  {
    id: "shalom",
    group: "god",
    name: "Yahweh Shalom",
    english: "The LORD is peace",
    reads: "The LORD Is Peace",
    original: "יְהוָה שָׁלוֹם",
    lang: "Hebrew",
    say: "YAH-weh shah-LOHM",
    strongs: "H3073",
    meaning: "The LORD is peace - wholeness, wellbeing, everything as it should be.",
    about: [
      "Gideon was threshing wheat in hiding, afraid of the Midianites, when the angel of the LORD came to him. Terrified that he had seen God, he heard: “Peace be with you. Do not be afraid, for you will not die” (Judges 6:23).",
      "“So Gideon built an altar to the LORD there and called it The LORD Is Peace” (Judges 6:24). Shalom is more than the end of fighting - it is wholeness, rest and being right with God.",
      "Jesus is the Prince of Peace (Isaiah 9:6): “Peace I leave with you; My peace I give to you” (John 14:27).",
    ],
    first: { ref: "Judges 6:24", note: "Gideon's altar." },
    verses: ["Numbers 6:24-26", "Judges 6:24", "Isaiah 26:3", "John 14:27"],
  },
  {
    id: "sabaoth",
    group: "god",
    name: "Yahweh Sabaoth",
    english: "The LORD of Hosts",
    reads: "the LORD of Hosts (NIV: the LORD Almighty)",
    original: "יְהוָה צְבָאוֹת",
    lang: "Hebrew",
    say: "YAH-weh tseh-vah-OHT",
    strongs: "H3068 + H6635",
    meaning: "The LORD of Hosts - commander of the armies of heaven.",
    about: [
      "“Hosts” are armies - the angels of heaven, the stars, and Israel's own armies - and the LORD commands them all. The NIV usually puts it as “the LORD Almighty”.",
      "Used more than 240 times, first at Shiloh in 1 Samuel 1:3, where Hannah prayed to Him for a son. David ran at Goliath saying, “I come against you in the name of the LORD of Hosts” (1 Samuel 17:45).",
      "It's the name the seraphim call out in Isaiah's vision: “Holy, holy, holy is the LORD of Hosts; all the earth is full of His glory” (Isaiah 6:3).",
    ],
    first: { ref: "1 Samuel 1:3", note: "Worship at Shiloh, in Hannah's story." },
    verses: ["1 Samuel 17:45", "Psalm 24:10", "Psalm 46:7", "Isaiah 6:3"],
  },
  {
    id: "raah",
    group: "god",
    name: "Yahweh Raah",
    english: "The LORD is my shepherd",
    reads: "the LORD is my shepherd",
    original: "יְהוָה רֹעִי",
    lang: "Hebrew",
    say: "YAH-weh roh-EE",
    strongs: "H7462",
    meaning: "The LORD my shepherd - who leads, feeds, protects and stays close.",
    about: [
      "David, who had kept his father's sheep, wrote: “The LORD is my shepherd; I shall not want” (Psalm 23:1).",
      "A shepherd leads to food and water, protects from danger, goes after the lost one and stays with the flock through the night. God promises to do all of this for His people (Isaiah 40:11; Ezekiel 34:11-16).",
      "Jesus takes the name for Himself: “I am the good shepherd. The good shepherd lays down His life for the sheep” (John 10:11).",
    ],
    first: { ref: "Genesis 48:15", note: "Jacob: “the God who has been my shepherd all my life”." },
    verses: ["Psalm 23:1", "Psalm 80:1", "Isaiah 40:11", "John 10:11"],
  },
  {
    id: "tsidkenu",
    group: "god",
    name: "Yahweh Tsidkenu",
    english: "The LORD our righteousness",
    reads: "The LORD Our Righteousness",
    original: "יְהוָה צִדְקֵנוּ",
    lang: "Hebrew",
    say: "YAH-weh tsid-KAY-noo",
    strongs: "H3072",
    meaning: "The LORD our righteousness - He makes us right with God.",
    about: [
      "Jeremiah promised a King from David's line, a righteous Branch: “And this is His name by which He will be called: The LORD Our Righteousness” (Jeremiah 23:6).",
      "Righteousness is being right with God. We cannot make ourselves righteous - God gives His own righteousness to us.",
      "“God made Him who knew no sin to be sin on our behalf, so that in Him we might become the righteousness of God” (2 Corinthians 5:21).",
    ],
    first: { ref: "Jeremiah 23:6", note: "The righteous Branch from David." },
    verses: ["Jeremiah 23:5-6", "Jeremiah 33:16", "1 Corinthians 1:30", "2 Corinthians 5:21"],
  },
  {
    id: "shammah",
    group: "god",
    name: "Yahweh Shammah",
    english: "The LORD is there",
    reads: "THE LORD IS THERE",
    original: "יְהוָה שָׁמָּה",
    lang: "Hebrew",
    say: "YAH-weh SHAH-mah",
    strongs: "H3074",
    meaning: "The LORD is there - God living among His people.",
    about: [
      "The last words of Ezekiel name the restored city of God: “And from that day on the name of the city will be: THE LORD IS THERE” (Ezekiel 48:35).",
      "Ezekiel had seen God's glory leave the temple because of the people's sin (Ezekiel 10). This name is the promise that He would come back and live among them.",
      "It comes true in Jesus, Immanuel - God with us - and finally in the new Jerusalem: “Behold, the dwelling place of God is with man” (Revelation 21:3).",
    ],
    first: { ref: "Ezekiel 48:35", note: "The last verse of Ezekiel." },
    verses: ["Psalm 46:1", "Ezekiel 48:35", "Matthew 28:20", "Revelation 21:3"],
  },
  {
    id: "i-am",
    group: "god",
    name: "I AM",
    english: "I AM WHO I AM",
    reads: "I AM",
    original: "אֶהְיֶה אֲשֶׁר אֶהְיֶה",
    lang: "Hebrew",
    translit: "Ehyeh asher ehyeh",
    say: "eh-YEH ah-SHER eh-YEH",
    strongs: "H1961",
    meaning: "I AM WHO I AM - the God who always was, is, and will be.",
    about: [
      "When Moses asked God's name at the burning bush, God said: “I AM WHO I AM. This is what you are to say to the Israelites: ‘I AM has sent me to you’” (Exodus 3:14).",
      "It means God depends on nothing and never changes. The name Yahweh comes from the same Hebrew verb, “to be”.",
      "Jesus said, “Truly, truly, I tell you… before Abraham was born, I am!” (John 8:58) - and the crowd picked up stones, because they understood He was taking God's own name.",
    ],
    first: { ref: "Exodus 3:14", note: "The burning bush." },
    verses: ["Exodus 3:14", "John 8:58", "Hebrews 13:8", "Revelation 1:8"],
  },
  {
    id: "holy-one",
    group: "god",
    name: "The Holy One of Israel",
    english: "Israel's Holy One",
    reads: "the Holy One of Israel",
    original: "קְדוֹשׁ יִשְׂרָאֵל",
    lang: "Hebrew",
    translit: "Kedosh Yisrael",
    say: "keh-DOHSH yis-rah-EL",
    strongs: "H6918",
    meaning: "The Holy One of Israel - perfectly pure, and yet bound to His people.",
    about: [
      "Isaiah's favourite name for God - he uses it 25 of its 31 times - after his vision of the throne, where the seraphim called out, “Holy, holy, holy is the LORD of Hosts” (Isaiah 6:3).",
      "Holy means set apart: completely pure, unlike anything else. Yet this Holy God ties Himself to His people as their Redeemer.",
      "“Do not be afraid, O worm Jacob, O few men of Israel. I will help you,” declares the LORD; “your Redeemer is the Holy One of Israel” (Isaiah 41:14).",
    ],
    first: { ref: "2 Kings 19:22", note: "Hezekiah's day, against Assyria." },
    verses: ["Isaiah 6:3", "Isaiah 12:6", "Isaiah 41:14", "Isaiah 43:3"],
  },
  {
    id: "ancient-of-days",
    group: "god",
    name: "Ancient of Days",
    english: "The Eternal Judge on the throne",
    reads: "the Ancient of Days",
    original: "עַתִּיק יוֹמִין",
    lang: "Aramaic",
    translit: "Attiq Yomin",
    say: "ah-TEEK yoh-MEEN",
    strongs: "H6268",
    meaning: "The Ancient of Days - eternal, wise, and Judge of all history.",
    about: [
      "Daniel saw God's throne room: “As I continued to watch, thrones were set in place, and the Ancient of Days took His seat. His clothing was white as snow, and the hair of His head was like pure wool” (Daniel 7:9).",
      "The empires of the world rise and fall like beasts in Daniel's vision, but the Ancient of Days stays on the throne and judges them.",
      "Then one like the Son of Man comes to the Ancient of Days and is given an everlasting kingdom (Daniel 7:13-14) - the title Jesus used for Himself more than any other.",
    ],
    first: { ref: "Daniel 7:9", note: "Daniel's vision of the throne." },
    verses: ["Daniel 7:9", "Daniel 7:13-14", "Daniel 7:22"],
  },
  {
    id: "abba",
    group: "god",
    name: "Abba, Father",
    english: "Father, dear Father",
    reads: "Abba, Father",
    original: "Ἀββα ὁ πατήρ",
    lang: "Aramaic & Greek",
    say: "AH-bah",
    strongs: "G5 + G3962",
    meaning: "Abba - the close, trusting word a child uses for their father.",
    about: [
      "Abba is Aramaic - the everyday language of Jesus - for “father”, the word a son or daughter used at home. In Gethsemane Jesus prayed, “Abba, Father… all things are possible for You” (Mark 14:36).",
      "God as Father is rare in the Old Testament but all through the New. Jesus taught us to pray, “Our Father in heaven, hallowed be Your name” (Matthew 6:9).",
      "By the Spirit, believers share His closeness: “you received the Spirit of sonship, by whom we cry, ‘Abba! Father!’” (Romans 8:15).",
    ],
    first: { ref: "Mark 14:36", note: "Jesus in Gethsemane." },
    verses: ["Matthew 6:9", "Mark 14:36", "Romans 8:15", "Galatians 4:6"],
  },
  {
    id: "father",
    group: "god",
    name: "Father",
    english: "God the Father",
    reads: "Father",
    original: "Πατήρ",
    lang: "Greek",
    translit: "Patēr",
    say: "pah-TAIR",
    strongs: "G3962",
    meaning: "God the Father - the Father of Jesus, and through Him our Father too.",
    about: [
      "Jesus speaks of God as “Father” more than 160 times in the Gospels - over 100 of them in John. It was the heart of His life: “I and the Father are one” (John 10:30).",
      "In the Old Testament God is sometimes called the Father of His people (Isaiah 63:16; Malachi 2:10), but Jesus made it personal. He taught us to pray, “Our Father in heaven, hallowed be Your name” (Matthew 6:9).",
      "Through Jesus we are brought into the family: “Behold what manner of love the Father has given to us, that we should be called children of God. And that is what we are!” (1 John 3:1).",
    ],
    first: { ref: "Matthew 5:16", note: "“glorify your Father in heaven”." },
    verses: ["Isaiah 64:8", "Matthew 6:9", "John 10:30", "John 14:9", "1 John 3:1"],
  },
  {
    id: "theos",
    group: "god",
    name: "Theos",
    english: "God",
    reads: "God",
    original: "Θεός",
    lang: "Greek",
    say: "theh-OSS",
    strongs: "G2316",
    meaning: "The New Testament's word for God.",
    about: [
      "Theos is used more than 1,300 times in the New Testament. The Greek Old Testament (the Septuagint) used it for Elohim.",
      "“In the beginning was the Word, and the Word was with God, and the Word was God” (John 1:1). And Thomas, seeing the risen Jesus, said, “My Lord and my God!” (John 20:28).",
    ],
    first: { ref: "Matthew 1:23", note: "Immanuel - “God with us”." },
    verses: ["John 1:1", "John 3:16", "John 20:28", "1 John 4:8"],
  },
  {
    id: "kyrios",
    group: "god",
    name: "Kyrios",
    english: "Lord",
    reads: "Lord",
    original: "Κύριος",
    lang: "Greek",
    say: "KOO-ree-oss",
    strongs: "G2962",
    meaning: "Lord - master and owner; the Greek word that stood for God's name.",
    about: [
      "Kyrios means lord, master or owner. The Greek Old Testament used it in place of God's name YHWH - so when the first Christians called Jesus “Lord”, they were giving Him God's own name.",
      "The earliest Christian confession was simply “Jesus is Lord” (Romans 10:9). One day “every tongue confess that Jesus Christ is Lord, to the glory of God the Father” (Philippians 2:11).",
    ],
    first: { ref: "Matthew 1:20", note: "“an angel of the Lord” appears to Joseph." },
    verses: ["Acts 2:36", "Romans 10:9", "1 Corinthians 12:3", "Philippians 2:11"],
  },
  {
    id: "holy-spirit",
    group: "god",
    name: "The Holy Spirit",
    english: "Ruach HaKodesh · Pneuma Hagion",
    reads: "the Holy Spirit, the Spirit of God",
    original: "רוּחַ הַקֹּדֶשׁ · Πνεῦμα Ἅγιον",
    lang: "Hebrew & Greek",
    translit: "Ruach HaKodesh",
    say: "ROO-akh hah-koh-DESH",
    strongs: "H7307 · G4151",
    meaning: "The Holy Spirit - God's own breath and presence, living in His people.",
    about: [
      "Ruach (Hebrew) and Pneuma (Greek) both mean breath, wind and spirit. At creation, “the Spirit of God was hovering over the surface of the waters” (Genesis 1:2).",
      "Jesus promised, “And I will ask the Father, and He will give you another Advocate to be with you forever” (John 14:16) - the Paraklētos: Helper, Counsellor, Comforter. He came at Pentecost (Acts 2).",
      "The Spirit gives new birth, teaches, comforts, gives gifts, and grows His fruit in us: “But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control” (Galatians 5:22-23).",
    ],
    first: { ref: "Genesis 1:2", note: "Hovering over the waters at creation." },
    verses: ["Genesis 1:2", "Psalm 51:11", "John 14:26", "Acts 2:4", "Galatians 5:22-23"],
  },

  // ── Names of Jesus ────────────────────────────────────────────
  {
    id: "jesus",
    group: "jesus",
    name: "Jesus",
    english: "The LORD saves",
    reads: "Jesus",
    original: "Ἰησοῦς · יֵשׁוּעַ",
    lang: "Greek & Hebrew",
    translit: "Iēsous · Yeshua",
    say: "yeh-SHOO-ah",
    strongs: "G2424",
    meaning: "Jesus - Yeshua, “the LORD saves”.",
    about: [
      "The angel told Joseph: “She will give birth to a Son, and you are to give Him the name Jesus, because He will save His people from their sins” (Matthew 1:21).",
      "Jesus is the Greek form of the Hebrew Yeshua - Joshua - meaning “the LORD saves”. Joshua led Israel into the promised land; Jesus leads His people into eternal life.",
      "“Salvation exists in no one else, for there is no other name under heaven given to men by which we must be saved” (Acts 4:12).",
    ],
    first: { ref: "Matthew 1:1", note: "“the genealogy of Jesus Christ”" },
    verses: ["Matthew 1:21", "Luke 1:31", "Acts 4:12", "Philippians 2:9-10"],
  },
  {
    id: "christ",
    group: "jesus",
    name: "Christ · Messiah",
    english: "The Anointed One",
    reads: "Christ, the Messiah",
    original: "Χριστός · מָשִׁיחַ",
    lang: "Greek & Hebrew",
    translit: "Christos · Mashiach",
    say: "mah-SHEE-akh",
    strongs: "G5547 · H4899",
    meaning: "Christ (Greek) and Messiah (Hebrew) both mean “the Anointed One”.",
    about: [
      "Christ is not Jesus' surname - it's a title. In Israel, prophets, priests and kings were anointed with oil to set them apart for God's work. The Messiah is the one King God promised to send from David's line - and Jesus is prophet, priest and king in one.",
      "Andrew ran to his brother Simon: “We have found the Messiah” (which is translated as Christ) (John 1:41). Simon Peter later answered Jesus: “You are the Christ, the Son of the living God” (Matthew 16:16).",
      "Daniel's prophecy of “the Messiah, the Prince” (Daniel 9:25) is one of the few places the Hebrew word is printed as Messiah in the Old Testament.",
    ],
    first: { ref: "Daniel 9:25", note: "“the Messiah, the Prince”, in Daniel's seventy weeks." },
    verses: ["Daniel 9:25", "Matthew 16:16", "John 1:41", "John 4:25-26"],
  },
  {
    id: "immanuel",
    group: "jesus",
    name: "Immanuel",
    english: "God with us",
    reads: "Immanuel",
    original: "עִמָּנוּ אֵל",
    lang: "Hebrew",
    say: "ih-MAN-yoo-el",
    strongs: "H6005 · G1694",
    meaning: "Immanuel - God with us.",
    about: [
      "Isaiah gave King Ahaz a sign: “Behold, the virgin will be with child and will give birth to a son, and will call Him Immanuel” (Isaiah 7:14).",
      "Matthew shows it coming true at Jesus' birth and explains the name: “and they will call Him Immanuel” (which means, “God with us”) (Matthew 1:23). God did not stay far away - He came to live among us.",
      "Matthew's Gospel ends with the same promise: “And surely I am with you always, even to the end of the age” (Matthew 28:20).",
    ],
    first: { ref: "Isaiah 7:14", note: "The sign given to Ahaz." },
    verses: ["Isaiah 7:14", "Matthew 1:23", "John 1:14", "Matthew 28:20"],
  },
  {
    id: "son-of-man",
    group: "jesus",
    name: "Son of Man",
    english: "Truly human, and the King from heaven",
    reads: "the Son of Man",
    original: "ὁ υἱὸς τοῦ ἀνθρώπου",
    lang: "Greek",
    translit: "ho huios tou anthrōpou",
    strongs: "G5207 + G444",
    meaning: "Jesus' favourite name for Himself - fully human, and the glorious King of Daniel 7.",
    about: [
      "Jesus calls Himself the Son of Man more than 80 times in the Gospels: “For the Son of Man came to seek and to save the lost” (Luke 19:10).",
      "It points back to Daniel's vision of one “like the Son of Man, coming with the clouds of heaven”, given an everlasting kingdom (Daniel 7:13-14).",
      "It holds both sides of who He is - one of us, born, tired, tempted and dying; and the King who will come again in glory (Mark 14:62).",
    ],
    first: { ref: "Matthew 8:20", note: "“the Son of Man has no place to lay His head.”" },
    verses: ["Daniel 7:13-14", "Mark 10:45", "Mark 14:62", "Luke 19:10"],
  },
  {
    id: "son-of-god",
    group: "jesus",
    name: "Son of God",
    english: "One with the Father",
    reads: "the Son of God",
    original: "ὁ υἱὸς τοῦ θεοῦ",
    lang: "Greek",
    translit: "ho huios tou theou",
    strongs: "G5207 + G2316",
    meaning: "The Son of God - sharing the Father's own nature, loved by Him.",
    about: [
      "At Jesus' baptism a voice from heaven said, “This is My beloved Son, in whom I am well pleased!” (Matthew 3:17).",
      "It means Jesus shares the Father's own nature - not a created son, but the one and only Son, who is Himself God (John 1:18).",
      "John wrote his whole Gospel “so that you may believe that Jesus is the Christ, the Son of God, and that by believing you may have life in His name” (John 20:31).",
    ],
    first: { ref: "Luke 1:35", note: "Gabriel to Mary: “the Holy One to be born will be called the Son of God.”" },
    verses: ["Luke 1:35", "Matthew 3:17", "Matthew 16:16", "John 20:31"],
  },
  {
    id: "word",
    group: "jesus",
    name: "The Word",
    english: "Logos - God speaking in a person",
    reads: "the Word",
    original: "ὁ Λόγος",
    lang: "Greek",
    translit: "ho Logos",
    say: "LOH-goss",
    strongs: "G3056",
    meaning: "The Word - God's perfect message to us, come in a person.",
    about: [
      "“In the beginning was the Word, and the Word was with God, and the Word was God” (John 1:1). “The Word became flesh and made His dwelling among us” (John 1:14).",
      "A word shows what's in the speaker's mind. God created by His word (“And God said…”), and through the Word all things were made (John 1:3). In Jesus, God speaks to us face to face.",
      "John sees Him again at the end, riding a white horse: “and His name is The Word of God” (Revelation 19:13).",
    ],
    first: { ref: "John 1:1", note: "“In the beginning was the Word.”" },
    verses: ["John 1:1", "John 1:14", "1 John 1:1", "Revelation 19:13"],
  },
  {
    id: "lamb",
    group: "jesus",
    name: "Lamb of God",
    english: "The sacrifice who takes sin away",
    reads: "the Lamb, the Lamb of God",
    original: "ὁ ἀμνὸς τοῦ θεοῦ",
    lang: "Greek",
    translit: "ho amnos tou theou",
    say: "am-NOSS too theh-OO",
    strongs: "G286 · G721",
    meaning: "The Lamb of God - the sacrifice God provides, who takes away sin.",
    about: [
      "John the Baptist saw Jesus coming and said, “Look, the Lamb of God, who takes away the sin of the world!” (John 1:29).",
      "It gathers up the whole Old Testament: the ram God provided in Isaac's place (Genesis 22), the Passover lamb whose blood saved Israel (Exodus 12), and the servant who “was led like a lamb to the slaughter” (Isaiah 53:7).",
      "In Revelation the Lamb who was slain stands at the centre of the throne, worshipped by all of heaven (Revelation 5:6-12).",
    ],
    first: { ref: "John 1:29", note: "John the Baptist at the Jordan." },
    verses: ["Exodus 12:13", "Isaiah 53:7", "John 1:29", "1 Peter 1:19", "Revelation 5:12"],
  },
  {
    id: "bread",
    group: "jesus",
    name: "The Bread of Life",
    english: "I am the bread of life",
    reads: "the bread of life",
    original: "ὁ ἄρτος τῆς ζωῆς",
    lang: "Greek",
    translit: "ho artos tēs zōēs",
    say: "AR-toss tays zoh-AYS",
    meaning: "Jesus satisfies the deepest hunger - He is life itself.",
    about: [
      "The day after feeding the five thousand, Jesus said: “I am the bread of life. Whoever comes to Me will never hunger, and whoever believes in Me will never thirst” (John 6:35).",
      "Israel ate manna, bread from heaven, in the wilderness - and still died. Jesus is the true bread from heaven: whoever “eats” Him - trusts Him - lives forever (John 6:49-51).",
    ],
    first: { ref: "John 6:35", note: "After feeding the five thousand." },
    verses: ["Exodus 16:4", "John 6:35", "John 6:51"],
  },
  {
    id: "light",
    group: "jesus",
    name: "The Light of the World",
    english: "I am the light of the world",
    reads: "the light of the world",
    original: "τὸ φῶς τοῦ κόσμου",
    lang: "Greek",
    translit: "to phōs tou kosmou",
    say: "toh FOHS too KOS-moo",
    meaning: "Jesus shows the way, brings what's hidden into the open, and drives darkness out.",
    about: [
      "At the Feast of Tabernacles, when great lamps were lit in the temple courts, Jesus said: “I am the light of the world. Whoever follows Me will never walk in the darkness, but will have the light of life” (John 8:12).",
      "Then He gave sight to a man born blind, to show it (John 9:5-7).",
      "He passes the light on to His people: “You are the light of the world” (Matthew 5:14).",
    ],
    first: { ref: "John 8:12", note: "In the temple courts." },
    verses: ["Isaiah 9:2", "John 1:4-5", "John 8:12", "Matthew 5:14"],
  },
  {
    id: "gate",
    group: "jesus",
    name: "The Gate",
    english: "I am the gate",
    reads: "the gate (the door)",
    original: "ἡ θύρα",
    lang: "Greek",
    translit: "hē thyra",
    say: "THOO-rah",
    meaning: "The one way into God's fold, and safety for those inside.",
    about: [
      "“I am the gate. If anyone enters through Me, he will be saved. He will come in and go out and find pasture” (John 10:9).",
      "At night a shepherd would lie across the opening of the sheepfold - he was the door. Nothing got in or out except past him. There is one way into God's fold, and it is Jesus.",
    ],
    first: { ref: "John 10:7", note: "Jesus and the sheepfold." },
    verses: ["John 10:7", "John 10:9", "John 14:6"],
  },
  {
    id: "shepherd",
    group: "jesus",
    name: "The Good Shepherd",
    english: "I am the good shepherd",
    reads: "the good shepherd",
    original: "ὁ ποιμὴν ὁ καλός",
    lang: "Greek",
    translit: "ho poimēn ho kalos",
    say: "poy-MAYN ho kah-LOSS",
    meaning: "The Shepherd who knows His sheep by name and lays down His life for them.",
    about: [
      "“I am the good shepherd. The good shepherd lays down His life for the sheep” (John 10:11). “I am the good shepherd. I know My sheep and My sheep know Me” (John 10:14).",
      "It answers Psalm 23 - “The LORD is my shepherd” - and God's promise in Ezekiel 34 to come and shepherd His scattered flock Himself.",
      "He is also the great Shepherd (Hebrews 13:20) and the Chief Shepherd who will come again (1 Peter 5:4).",
    ],
    first: { ref: "John 10:11", note: "Jesus and the sheepfold." },
    verses: ["Psalm 23:1", "Ezekiel 34:11-12", "John 10:11", "1 Peter 5:4"],
  },
  {
    id: "resurrection",
    group: "jesus",
    name: "The Resurrection and the Life",
    english: "I am the resurrection and the life",
    reads: "the resurrection and the life",
    original: "ἡ ἀνάστασις καὶ ἡ ζωή",
    lang: "Greek",
    translit: "hē anastasis kai hē zōē",
    say: "ah-NAS-tah-sis kye hay zoh-AY",
    meaning: "Death does not have the last word - Jesus does.",
    about: [
      "Outside Lazarus' tomb, Jesus said to Martha: “I am the resurrection and the life. Whoever believes in Me will live, even though he dies” (John 11:25). Then He called Lazarus out of the grave.",
      "Days later He rose from the dead Himself - the firstfruits of everyone who will be raised (1 Corinthians 15:20).",
    ],
    first: { ref: "John 11:25", note: "At Lazarus' tomb in Bethany." },
    verses: ["John 11:25-26", "1 Corinthians 15:20-22", "Revelation 1:18"],
  },
  {
    id: "way",
    group: "jesus",
    name: "The Way, the Truth and the Life",
    english: "I am the way and the truth and the life",
    reads: "the way and the truth and the life",
    original: "ἡ ὁδὸς καὶ ἡ ἀλήθεια καὶ ἡ ζωή",
    lang: "Greek",
    translit: "hē hodos kai hē alētheia kai hē zōē",
    say: "hoh-DOSS, ah-LAY-thee-ah, zoh-AY",
    meaning: "Jesus is the way to the Father - not only a teacher of the way.",
    about: [
      "On the night before the cross Thomas asked how they could know the way. Jesus answered, “I am the way and the truth and the life. No one comes to the Father except through Me” (John 14:6).",
      "Before they were called Christians, the first believers were simply known as followers of “the Way” (Acts 9:2).",
    ],
    first: { ref: "John 14:6", note: "The Last Supper." },
    verses: ["John 14:6", "Acts 4:12", "Hebrews 10:19-20"],
  },
  {
    id: "vine",
    group: "jesus",
    name: "The True Vine",
    english: "I am the vine",
    reads: "the true vine",
    original: "ἡ ἄμπελος ἡ ἀληθινή",
    lang: "Greek",
    translit: "hē ampelos hē alēthinē",
    say: "AM-peh-loss",
    meaning: "Stay joined to Jesus and you will bear fruit; apart from Him, nothing.",
    about: [
      "“I am the vine and you are the branches. The one who remains in Me, and I in him, will bear much fruit. For apart from Me you can do nothing” (John 15:5).",
      "Israel was pictured as God's vine (Psalm 80:8; Isaiah 5:1-7) that failed to bear good fruit. Jesus is the true vine, and His Father is the gardener.",
    ],
    first: { ref: "John 15:1", note: "On the way to Gethsemane." },
    verses: ["Isaiah 5:7", "John 15:1", "John 15:5"],
  },
  {
    id: "alpha-omega",
    group: "jesus",
    name: "Alpha and Omega",
    english: "The First and the Last",
    reads: "the Alpha and the Omega",
    original: "τὸ Ἄλφα καὶ τὸ Ὦ",
    lang: "Greek",
    say: "AL-fah and oh-MAY-gah",
    strongs: "G1 + G5598",
    meaning: "The A to Z - before everything, and with the last word.",
    about: [
      "Alpha and Omega are the first and last letters of the Greek alphabet - like saying “A to Z”. “I am the Alpha and the Omega, the First and the Last, the Beginning and the End” (Revelation 22:13).",
      "God said the same through Isaiah: “I am the first and I am the last, and there is no God but Me” (Isaiah 44:6). Jesus takes these words for Himself.",
    ],
    first: { ref: "Revelation 1:8", note: "The opening of Revelation." },
    verses: ["Isaiah 44:6", "Revelation 1:8", "Revelation 21:6", "Revelation 22:13"],
  },
  {
    id: "lion",
    group: "jesus",
    name: "Lion of the Tribe of Judah",
    english: "The conquering King",
    reads: "the Lion of the tribe of Judah",
    original: "ὁ λέων ὁ ἐκ τῆς φυλῆς Ἰούδα",
    lang: "Greek",
    meaning: "A Lion in power, a Lamb in sacrifice.",
    about: [
      "In heaven John wept because no one was worthy to open the scroll. Then an elder said, “Do not weep! Behold, the Lion of the tribe of Judah, the Root of David, has triumphed to open the scroll and its seven seals” (Revelation 5:5) - and John turned and saw a Lamb, looking as if it had been slain.",
      "It goes back to Jacob's blessing over his son: “Judah is a young lion” and the sceptre will not depart from Judah (Genesis 49:9-10). Jesus is the King from Judah's line.",
    ],
    first: { ref: "Genesis 49:9", note: "Jacob blesses Judah." },
    verses: ["Genesis 49:9-10", "Revelation 5:5"],
  },
  {
    id: "king-of-kings",
    group: "jesus",
    name: "King of Kings and Lord of Lords",
    english: "Ruler over every ruler",
    reads: "King of kings and Lord of lords",
    lang: "Greek",
    strongs: "G935 + G2962",
    meaning: "Every earthly ruler answers to Him.",
    about: [
      "As Jesus rides out from heaven: “And He has a name written on His robe and on His thigh: KING OF KINGS AND LORD OF LORDS” (Revelation 19:16).",
      "Paul calls God “the blessed and only Sovereign One, the King of kings and Lord of lords” (1 Timothy 6:15).",
      "Pilate's sign over the cross read “Jesus of Nazareth, the King of the Jews” (John 19:19) - the King who first wore a crown of thorns.",
    ],
    first: { ref: "Deuteronomy 10:17", note: "“God of gods and Lord of lords.”" },
    verses: ["Deuteronomy 10:17", "1 Timothy 6:15", "Revelation 17:14", "Revelation 19:16"],
  },
  {
    id: "son-of-david",
    group: "jesus",
    name: "Son of David",
    english: "The promised King from David's line",
    reads: "the Son of David",
    lang: "Greek",
    strongs: "G5207 + G1138",
    meaning: "The King God promised David would come from his family, to reign forever.",
    about: [
      "God promised David: “Your house and kingdom will endure forever before Me, and your throne will be established forever” (2 Samuel 7:16). So the Messiah would be a son - a descendant - of David.",
      "Matthew opens with “the genealogy of Jesus Christ, the son of David, the son of Abraham” (Matthew 1:1). Blind Bartimaeus cried, “Jesus, Son of David, have mercy on me!” (Mark 10:47).",
    ],
    first: { ref: "Matthew 1:1", note: "The first verse of the New Testament." },
    verses: ["2 Samuel 7:16", "Isaiah 11:1", "Matthew 1:1", "Mark 10:47"],
  },
  {
    id: "rabbi",
    group: "jesus",
    name: "Rabbi · Rabboni",
    english: "My Teacher",
    reads: "Rabbi, Teacher",
    original: "Ῥαββί · Ῥαββουνί",
    lang: "Hebrew in Greek",
    say: "rah-BEE",
    strongs: "G4461 · G4462",
    meaning: "My teacher, my master - how His disciples spoke to Him.",
    about: [
      "Rabbi means “my teacher” or “my master” - a respectful name for a teacher of the Scriptures. The first disciples asked Him, “Rabbi” (which means Teacher), “where are You staying?” (John 1:38).",
      "On the first Easter morning, when Jesus said her name, Mary Magdalene turned and cried out in Aramaic, “Rabboni!” (which means Teacher) (John 20:16).",
    ],
    first: { ref: "John 1:38", note: "The first disciples follow Jesus." },
    verses: ["John 1:38", "John 1:49", "John 3:2", "John 20:16"],
  },
  {
    id: "isaiah-9-6",
    group: "jesus",
    name: "Wonderful Counsellor, Mighty God, Everlasting Father, Prince of Peace",
    english: "The four names of Isaiah 9:6",
    reads: "Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace",
    original: "פֶּלֶא יוֹעֵץ אֵל גִּבּוֹר אֲבִיעַד שַׂר־שָׁלוֹם",
    lang: "Hebrew",
    translit: "Pele Yoetz, El Gibbor, Avi-ad, Sar Shalom",
    say: "PEH-leh yoh-ETS, el gib-BOHR, ah-vee-AHD, sar shah-LOHM",
    meaning: "Four names for the promised child - written about 700 years before He was born.",
    about: [
      "“For unto us a child is born, unto us a son is given, and the government will be upon His shoulders. And He will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace” (Isaiah 9:6).",
      "Wonderful Counsellor (Pele Yoetz): perfect wisdom, beyond understanding. Mighty God (El Gibbor): God the warrior who wins the battle. Everlasting Father (Avi-ad): He cares for His people forever. Prince of Peace (Sar Shalom): the ruler whose kingdom is peace.",
    ],
    first: { ref: "Isaiah 9:6", note: "Isaiah's promise of the child." },
    verses: ["Isaiah 9:6-7", "Luke 2:11", "Ephesians 2:14"],
  },
  {
    id: "bridegroom",
    group: "jesus",
    name: "The Bridegroom",
    english: "Jesus and His bride, the church",
    reads: "the bridegroom",
    original: "ὁ νυμφίος",
    lang: "Greek",
    translit: "ho nymphios",
    say: "noom-FEE-oss",
    strongs: "G3566",
    meaning: "Jesus loves His people the way a bridegroom loves his bride.",
    about: [
      "Asked why His disciples didn't fast, Jesus said, “How can the guests of the bridegroom mourn while He is with them?” (Matthew 9:15). John the Baptist called himself the friend of the bridegroom (John 3:29).",
      "God called Himself Israel's husband (Isaiah 54:5; Hosea 2:19). The church is the bride of Christ (Ephesians 5:25-27), and history ends with the wedding supper of the Lamb (Revelation 19:7-9).",
    ],
    first: { ref: "Matthew 9:15", note: "A question about fasting." },
    verses: ["Isaiah 62:5", "Matthew 9:15", "John 3:29", "Revelation 19:7"],
  },
  {
    id: "high-priest",
    group: "jesus",
    name: "Great High Priest",
    english: "Who brings us to God",
    reads: "high priest",
    original: "ἀρχιερεύς",
    lang: "Greek",
    translit: "archiereus",
    strongs: "G749",
    meaning: "He offered Himself once for all, and always lives to pray for us.",
    about: [
      "Israel's high priest went into the Most Holy Place once a year with blood for the people's sins. Hebrews shows Jesus as the great high priest: “since we have a great high priest who has passed through the heavens, Jesus the Son of God” (Hebrews 4:14).",
      "He understands our weakness - “we have one who was tempted in every way that we are, yet was without sin” (Hebrews 4:15) - and “He always lives to intercede for them” (Hebrews 7:25).",
      "He is a priest in the order of Melchizedek (Psalm 110:4; Hebrews 7), the king-priest who blessed Abram.",
    ],
    first: { ref: "Hebrews 2:17", note: "“a merciful and faithful high priest”." },
    verses: ["Psalm 110:4", "Hebrews 4:14-16", "Hebrews 7:25", "Hebrews 9:11-12"],
  },
  {
    id: "cornerstone",
    group: "jesus",
    name: "The Cornerstone",
    english: "The stone everything is built on",
    reads: "the cornerstone",
    original: "ἀκρογωνιαῖος",
    lang: "Greek",
    translit: "akrogōniaios",
    strongs: "G204",
    meaning: "The first stone laid - every other stone is lined up by Him.",
    about: [
      "“The stone the builders rejected has become the cornerstone” (Psalm 118:22) - Jesus applied it to Himself (Matthew 21:42).",
      "A cornerstone was the first stone laid, and every other stone was set by it. The church is built on the apostles and prophets, “with Christ Jesus Himself as the cornerstone” (Ephesians 2:20).",
    ],
    first: { ref: "Psalm 118:22", note: "The rejected stone." },
    verses: ["Psalm 118:22", "Isaiah 28:16", "Ephesians 2:20", "1 Peter 2:6"],
  },
  {
    id: "saviour",
    group: "jesus",
    name: "Saviour",
    english: "The One who rescues",
    reads: "Savior",
    original: "Σωτήρ",
    lang: "Greek",
    translit: "Sōtēr",
    say: "soh-TAIR",
    strongs: "G4990",
    meaning: "The Saviour of the world - God Himself come to rescue.",
    about: [
      "The angel told the shepherds: “Today in the City of David a Savior has been born to you. He is Christ the Lord!” (Luke 2:11).",
      "In the Old Testament God says, “I, yes I, am the LORD, and there is no Savior but Me” (Isaiah 43:11). Jesus is that Saviour.",
      "After meeting Him, the Samaritans of Sychar said, “and we know that this man truly is the Savior of the world” (John 4:42).",
    ],
    first: { ref: "Luke 1:47", note: "Mary: “my spirit rejoices in God my Savior”." },
    verses: ["Isaiah 43:11", "Luke 2:11", "John 4:42", "Titus 2:13"],
  },
];

export const nameById = (id: string) => NAMES.find((n) => n.id === id) ?? null;
