// The site's Worker: OpenNext's Next.js handler, plus a nightly Cron
// Trigger (wrangler.jsonc "triggers") that backs up The Study to the
// private R2 bucket - see src/lib/study/backup-core.ts.
// https://opennext.js.org/cloudflare/howtos/custom-worker

// @ts-ignore - generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { runBackup } from "./src/lib/study/backup-core";

export default {
  fetch: handler.fetch,
  async scheduled(_event: unknown, env: { DB: never; BACKUPS: never }, ctx: { waitUntil(p: Promise<unknown>): void }) {
    ctx.waitUntil(runBackup(env.DB, env.BACKUPS, "nightly"));
  },
};

// @ts-ignore - Durable Objects from the OpenNext build
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
