// The site's Worker: OpenNext's Next.js handler, plus two Cron Triggers
// (wrangler.jsonc "triggers"): at 02:00 UTC a backup of The Study to the
// private R2 bucket (src/lib/study/backup-core.ts), and every hour the
// members' daily reading reminders (src/lib/study/push.ts).
// https://opennext.js.org/cloudflare/howtos/custom-worker

// @ts-ignore - generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { runBackup } from "./src/lib/study/backup-core";
import { eraseMemberBin } from "./src/lib/study/bin-erase";
import { runReminders } from "./src/lib/study/push";

const BACKUP_CRON = "0 2 * * *";

export default {
  // Always the secure address: logins and member sessions need https.
  // (LOCAL_DEV is set in .dev.vars, so `wrangler dev` on plain http still works.)
  fetch(req: Request, env: { LOCAL_DEV?: string }, ctx: unknown) {
    const url = new URL(req.url);
    if (!env.LOCAL_DEV && url.protocol === "http:" && url.hostname !== "localhost" && url.hostname !== "127.0.0.1") {
      url.protocol = "https:";
      return Response.redirect(url.toString(), 301);
    }
    return handler.fetch(req, env, ctx);
  },
  async scheduled(
    event: { cron: string },
    env: { DB: never; BACKUPS: never; VAPID_PRIVATE_JWK?: string },
    ctx: { waitUntil(p: Promise<unknown>): void },
  ) {
    // Nightly: back everything up, then erase members' emptied bin items.
    if (event.cron === BACKUP_CRON) ctx.waitUntil(runBackup(env.DB, env.BACKUPS, "nightly").then(() => eraseMemberBin(env.DB)));
    else ctx.waitUntil(runReminders(env.DB, env.VAPID_PRIVATE_JWK));
  },
};

// @ts-ignore - Durable Objects from the OpenNext build
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
