// Chronological-Bible reading plan, 365 days.
// Following the canonical chronological order used by the Blue Letter Bible
// "Chronological" plan (Genesis split for Job, then Exodus → Joshua → Judges →
// Samuel → Kings interleaved with the writing prophets and Psalms → exile →
// Gospels interleaved → Acts → epistles → Revelation).
// Each entry: { day, passage, theme }. Theme is a short one-liner.

export interface PlanDay {
  day: number;
  passage: string;
  theme?: string;
}

export const CHRONO_PLAN: PlanDay[] = [
  { day: 1, passage: "Genesis 1-3", theme: "Creation, the Fall" },
  { day: 2, passage: "Genesis 4-7", theme: "Cain, Seth, the Flood" },
  { day: 3, passage: "Genesis 8-11", theme: "After the flood, Babel" },
  { day: 4, passage: "Job 1-5", theme: "Job afflicted, friends arrive" },
  { day: 5, passage: "Job 6-9", theme: "Job answers, Bildad" },
  { day: 6, passage: "Job 10-13", theme: "Job's complaint" },
  { day: 7, passage: "Job 14-16", theme: "Job's despair, Eliphaz" },
  { day: 8, passage: "Job 17-20", theme: "Zophar speaks" },
  { day: 9, passage: "Job 21-23", theme: "Job answers" },
  { day: 10, passage: "Job 24-28", theme: "Wisdom — where shall it be found?" },
  { day: 11, passage: "Job 29-31", theme: "Job's defense" },
  { day: 12, passage: "Job 32-34", theme: "Elihu speaks" },
  { day: 13, passage: "Job 35-37", theme: "Elihu continues" },
  { day: 14, passage: "Job 38-39", theme: "The Lord answers from the whirlwind" },
  { day: 15, passage: "Job 40-42", theme: "Job repents, is restored" },
  { day: 16, passage: "Genesis 12-15", theme: "Abram called" },
  { day: 17, passage: "Genesis 16-18", theme: "Hagar, Ishmael, the three visitors" },
  { day: 18, passage: "Genesis 19-21", theme: "Sodom, Isaac born" },
  { day: 19, passage: "Genesis 22-24", theme: "Abraham offers Isaac" },
  { day: 20, passage: "Genesis 25-26", theme: "Jacob and Esau" },
  { day: 21, passage: "Genesis 27-29", theme: "Jacob flees, marries" },
  { day: 22, passage: "Genesis 30-31", theme: "Jacob's family, returns" },
  { day: 23, passage: "Genesis 32-34", theme: "Wrestling with God" },
  { day: 24, passage: "Genesis 35-37", theme: "Joseph's dreams" },
  { day: 25, passage: "Genesis 38-40", theme: "Joseph in Egypt" },
  { day: 26, passage: "Genesis 41-42", theme: "Pharaoh's dreams" },
  { day: 27, passage: "Genesis 43-45", theme: "Joseph reveals himself" },
  { day: 28, passage: "Genesis 46-47", theme: "Israel to Egypt" },
  { day: 29, passage: "Genesis 48-50", theme: "Jacob's blessing, Joseph's bones" },
  { day: 30, passage: "Exodus 1-3", theme: "Moses called" },
  { day: 31, passage: "Exodus 4-6", theme: "Moses returns to Egypt" },
  { day: 32, passage: "Exodus 7-9", theme: "First plagues" },
  { day: 33, passage: "Exodus 10-12", theme: "Passover" },
  { day: 34, passage: "Exodus 13-15", theme: "Red Sea crossing" },
  { day: 35, passage: "Exodus 16-18", theme: "Manna, water from the rock" },
  { day: 36, passage: "Exodus 19-21", theme: "Sinai, the Ten Words" },
  { day: 37, passage: "Exodus 22-24", theme: "Covenant code" },
  { day: 38, passage: "Exodus 25-27", theme: "Tabernacle plans" },
  { day: 39, passage: "Exodus 28-29", theme: "Priestly garments" },
  { day: 40, passage: "Exodus 30-32", theme: "Golden calf" },
  { day: 41, passage: "Exodus 33-35", theme: "Show me your glory" },
  { day: 42, passage: "Exodus 36-38", theme: "Tabernacle built" },
  { day: 43, passage: "Exodus 39-40", theme: "Glory fills the tent" },
  { day: 44, passage: "Leviticus 1-4", theme: "Offerings" },
  { day: 45, passage: "Leviticus 5-7", theme: "Sin and guilt offerings" },
  { day: 46, passage: "Leviticus 8-10", theme: "Aaron consecrated, Nadab & Abihu" },
  { day: 47, passage: "Leviticus 11-13", theme: "Clean and unclean" },
  { day: 48, passage: "Leviticus 14-15", theme: "Cleansing rituals" },
  { day: 49, passage: "Leviticus 16-18", theme: "Day of Atonement" },
  { day: 50, passage: "Leviticus 19-21", theme: "Be holy, for I am holy" },
  { day: 51, passage: "Leviticus 22-23", theme: "Feasts of the LORD" },
  { day: 52, passage: "Leviticus 24-25", theme: "Sabbath year, Jubilee" },
  { day: 53, passage: "Leviticus 26-27", theme: "Blessings and curses" },
  { day: 54, passage: "Numbers 1-2", theme: "Census, camp order" },
  { day: 55, passage: "Numbers 3-4", theme: "Levites set apart" },
  { day: 56, passage: "Numbers 5-6", theme: "Nazirite vow, Aaronic blessing" },
  { day: 57, passage: "Numbers 7", theme: "Tribal offerings" },
  { day: 58, passage: "Numbers 8-10", theme: "Cloud leads them out" },
  { day: 59, passage: "Numbers 11-13", theme: "Complaints, the twelve spies" },
  { day: 60, passage: "Numbers 14-15; Psalm 90", theme: "Forty years in the wilderness" },
  { day: 61, passage: "Numbers 16-17", theme: "Korah's rebellion" },
  { day: 62, passage: "Numbers 18-20", theme: "Water from the rock, Moses strikes it" },
  { day: 63, passage: "Numbers 21-22", theme: "Bronze serpent, Balaam" },
  { day: 64, passage: "Numbers 23-25", theme: "Balaam's oracles, Phinehas" },
  { day: 65, passage: "Numbers 26-27", theme: "Second census, Joshua chosen" },
  { day: 66, passage: "Numbers 28-30", theme: "Offerings, vows" },
  { day: 67, passage: "Numbers 31-32", theme: "Midianite war" },
  { day: 68, passage: "Numbers 33-34", theme: "Journey summary, borders" },
  { day: 69, passage: "Numbers 35-36", theme: "Cities of refuge" },
  { day: 70, passage: "Deuteronomy 1-2", theme: "Moses recounts" },
  { day: 71, passage: "Deuteronomy 3-4", theme: "Take heed, remember" },
  { day: 72, passage: "Deuteronomy 5-7", theme: "Hear, O Israel" },
  { day: 73, passage: "Deuteronomy 8-10", theme: "Man does not live by bread alone" },
  { day: 74, passage: "Deuteronomy 11-13", theme: "Choose this day" },
  { day: 75, passage: "Deuteronomy 14-16", theme: "Tithes, feasts" },
  { day: 76, passage: "Deuteronomy 17-20", theme: "Judges, kings, prophets" },
  { day: 77, passage: "Deuteronomy 21-23", theme: "Civil laws" },
  { day: 78, passage: "Deuteronomy 24-27", theme: "Mercy, blessing and curse" },
  { day: 79, passage: "Deuteronomy 28-29", theme: "Covenant blessings and curses" },
  { day: 80, passage: "Deuteronomy 30-31", theme: "Choose life" },
  { day: 81, passage: "Deuteronomy 32-34", theme: "Moses' song and death" },
  { day: 82, passage: "Joshua 1-4", theme: "Be strong and courageous; Jordan crossed" },
  { day: 83, passage: "Joshua 5-8", theme: "Jericho, Ai" },
  { day: 84, passage: "Joshua 9-11", theme: "Conquest" },
  { day: 85, passage: "Joshua 12-15", theme: "Land divided" },
  { day: 86, passage: "Joshua 16-18", theme: "Inheritance" },
  { day: 87, passage: "Joshua 19-21", theme: "Cities of refuge, Levite cities" },
  { day: 88, passage: "Joshua 22-24", theme: "Choose this day whom you serve" },
  { day: 89, passage: "Judges 1-2", theme: "Failure to drive out" },
  { day: 90, passage: "Judges 3-5", theme: "Othniel, Ehud, Deborah" },
  { day: 91, passage: "Judges 6-7", theme: "Gideon" },
  { day: 92, passage: "Judges 8-9", theme: "Gideon, Abimelech" },
  { day: 93, passage: "Judges 10-12", theme: "Jephthah" },
  { day: 94, passage: "Judges 13-15", theme: "Samson" },
  { day: 95, passage: "Judges 16-18", theme: "Samson's end" },
  { day: 96, passage: "Judges 19-21", theme: "Civil war in Israel" },
  { day: 97, passage: "Ruth 1-4", theme: "Redeemer" },
  { day: 98, passage: "1 Samuel 1-3", theme: "Samuel called" },
  { day: 99, passage: "1 Samuel 4-8", theme: "Ark captured, give us a king" },
  { day: 100, passage: "1 Samuel 9-12", theme: "Saul anointed" },
  { day: 101, passage: "1 Samuel 13-14", theme: "Jonathan's faith" },
  { day: 102, passage: "1 Samuel 15-17", theme: "Saul rejected, David anointed, Goliath" },
  { day: 103, passage: "1 Samuel 18-20", theme: "David and Jonathan" },
  { day: 104, passage: "1 Samuel 21-24; Psalm 52, 34, 56", theme: "David flees" },
  { day: 105, passage: "1 Samuel 25-27; Psalm 17, 35, 54", theme: "David spares Saul" },
  { day: 106, passage: "1 Samuel 28-31; Psalm 18", theme: "Saul's end" },
  { day: 107, passage: "2 Samuel 1-4", theme: "David king of Judah" },
  { day: 108, passage: "2 Samuel 5-7; Psalm 132", theme: "Davidic covenant" },
  { day: 109, passage: "2 Samuel 8-10; Psalm 60", theme: "Victories" },
  { day: 110, passage: "2 Samuel 11-12; Psalm 51", theme: "Bathsheba, Nathan, repentance" },
  { day: 111, passage: "2 Samuel 13-15", theme: "Amnon, Absalom" },
  { day: 112, passage: "2 Samuel 16-18; Psalm 3", theme: "Absalom's revolt" },
  { day: 113, passage: "2 Samuel 19-21", theme: "David restored" },
  { day: 114, passage: "2 Samuel 22-24; Psalm 18", theme: "David's song" },
  { day: 115, passage: "Psalms 1-7", theme: "Blessed is the man" },
  { day: 116, passage: "Psalms 8-14", theme: "The heavens declare" },
  { day: 117, passage: "Psalms 15-19", theme: "Who shall ascend?" },
  { day: 118, passage: "Psalms 20-25", theme: "The Lord is my shepherd" },
  { day: 119, passage: "Psalms 26-31", theme: "The Lord is my light" },
  { day: 120, passage: "Psalms 32-37", theme: "Delight yourself in the Lord" },
  { day: 121, passage: "Psalms 38-42", theme: "Hope in God" },
  { day: 122, passage: "Psalms 43-49", theme: "God is our refuge" },
  { day: 123, passage: "Psalms 50-55", theme: "Create in me a clean heart" },
  { day: 124, passage: "Psalms 56-61", theme: "In God I trust" },
  { day: 125, passage: "Psalms 62-67", theme: "For God alone my soul waits" },
  { day: 126, passage: "Psalms 68-71", theme: "Sing to God" },
  { day: 127, passage: "Psalms 72-77", theme: "May his name endure" },
  { day: 128, passage: "1 Kings 1-3", theme: "Solomon king, asks for wisdom" },
  { day: 129, passage: "1 Kings 4-6; 2 Chronicles 1", theme: "Solomon's wisdom, temple" },
  { day: 130, passage: "1 Kings 7-8; 2 Chronicles 2-5", theme: "Temple finished" },
  { day: 131, passage: "1 Kings 9-11; 2 Chronicles 6-9", theme: "Solomon's later years" },
  { day: 132, passage: "Proverbs 1-3", theme: "Trust in the Lord" },
  { day: 133, passage: "Proverbs 4-6", theme: "Guard your heart" },
  { day: 134, passage: "Proverbs 7-9", theme: "Wisdom's call" },
  { day: 135, passage: "Proverbs 10-12", theme: "Of the righteous" },
  { day: 136, passage: "Proverbs 13-15", theme: "A gentle answer" },
  { day: 137, passage: "Proverbs 16-18", theme: "Pride before destruction" },
  { day: 138, passage: "Proverbs 19-21", theme: "Better a poor man" },
  { day: 139, passage: "Proverbs 22-24", theme: "Sayings of the wise" },
  { day: 140, passage: "Proverbs 25-27", theme: "Apples of gold" },
  { day: 141, passage: "Proverbs 28-31", theme: "An excellent wife" },
  { day: 142, passage: "Ecclesiastes 1-6", theme: "Vanity of vanities" },
  { day: 143, passage: "Ecclesiastes 7-12", theme: "Remember your Creator" },
  { day: 144, passage: "Song of Solomon", theme: "Love song" },
  { day: 145, passage: "1 Kings 12-14; 2 Chronicles 10-12", theme: "Kingdom divided" },
  { day: 146, passage: "1 Kings 15-16; 2 Chronicles 13-16", theme: "Asa" },
  { day: 147, passage: "1 Kings 17-19", theme: "Elijah" },
  { day: 148, passage: "1 Kings 20-21", theme: "Naboth's vineyard" },
  { day: 149, passage: "1 Kings 22; 2 Chronicles 17-20", theme: "Jehoshaphat" },
  { day: 150, passage: "2 Kings 1-4", theme: "Elijah taken, Elisha" },
  { day: 151, passage: "2 Kings 5-8", theme: "Naaman healed" },
  { day: 152, passage: "2 Kings 9-12; 2 Chronicles 21-24", theme: "Jehu, Joash" },
  { day: 153, passage: "Joel 1-3", theme: "The day of the Lord" },
  { day: 154, passage: "Jonah 1-4", theme: "Reluctant prophet" },
  { day: 155, passage: "Amos 1-5", theme: "Let justice roll down" },
  { day: 156, passage: "Amos 6-9", theme: "Famine of hearing the word" },
  { day: 157, passage: "Hosea 1-7", theme: "Gomer, return" },
  { day: 158, passage: "Hosea 8-14", theme: "I will heal their apostasy" },
  { day: 159, passage: "2 Kings 13-14; 2 Chronicles 25", theme: "Jeroboam II, Amaziah" },
  { day: 160, passage: "2 Kings 15-17; 2 Chronicles 26-28", theme: "Fall of Samaria" },
  { day: 161, passage: "Isaiah 1-4", theme: "Come let us reason" },
  { day: 162, passage: "Isaiah 5-8", theme: "Holy, holy, holy" },
  { day: 163, passage: "Isaiah 9-12", theme: "A child is born" },
  { day: 164, passage: "Isaiah 13-17", theme: "Oracles" },
  { day: 165, passage: "Isaiah 18-22", theme: "Burdens of the nations" },
  { day: 166, passage: "Isaiah 23-27", theme: "The city of God" },
  { day: 167, passage: "Isaiah 28-30", theme: "In quietness and trust" },
  { day: 168, passage: "Isaiah 31-35", theme: "The desert shall bloom" },
  { day: 169, passage: "Isaiah 36-39; 2 Kings 18-20", theme: "Hezekiah" },
  { day: 170, passage: "Isaiah 40-43", theme: "Comfort, my people" },
  { day: 171, passage: "Isaiah 44-48", theme: "Cyrus, the only God" },
  { day: 172, passage: "Isaiah 49-53", theme: "The suffering servant" },
  { day: 173, passage: "Isaiah 54-58", theme: "Free invitation, true fast" },
  { day: 174, passage: "Isaiah 59-63", theme: "Arise, shine" },
  { day: 175, passage: "Isaiah 64-66", theme: "New heavens, new earth" },
  { day: 176, passage: "Micah 1-7", theme: "What does the Lord require" },
  { day: 177, passage: "Nahum 1-3", theme: "Nineveh falls" },
  { day: 178, passage: "2 Kings 21-23; 2 Chronicles 33-35", theme: "Josiah's reforms" },
  { day: 179, passage: "Zephaniah 1-3", theme: "Sing aloud, O daughter of Zion" },
  { day: 180, passage: "Habakkuk 1-3", theme: "The just shall live by faith" },
  { day: 181, passage: "Jeremiah 1-3", theme: "Before I formed you" },
  { day: 182, passage: "Jeremiah 4-6", theme: "Circumcise your hearts" },
  { day: 183, passage: "Jeremiah 7-9", theme: "Trust not in lying words" },
  { day: 184, passage: "Jeremiah 10-13", theme: "Idols are senseless" },
  { day: 185, passage: "Jeremiah 14-17", theme: "Drought, sabbath" },
  { day: 186, passage: "Jeremiah 18-22", theme: "Potter's house" },
  { day: 187, passage: "Jeremiah 23-25", theme: "False shepherds" },
  { day: 188, passage: "Jeremiah 26-29", theme: "Plans to prosper you" },
  { day: 189, passage: "Jeremiah 30-31", theme: "New covenant" },
  { day: 190, passage: "Jeremiah 32-34", theme: "Field at Anathoth" },
  { day: 191, passage: "Jeremiah 35-37", theme: "Rechabites" },
  { day: 192, passage: "Jeremiah 38-40; 2 Kings 24-25", theme: "Jerusalem falls" },
  { day: 193, passage: "Jeremiah 41-45", theme: "Remnant flees to Egypt" },
  { day: 194, passage: "Jeremiah 46-48", theme: "Oracles against the nations" },
  { day: 195, passage: "Jeremiah 49-50", theme: "Against Babylon" },
  { day: 196, passage: "Jeremiah 51-52", theme: "Babylon's fall" },
  { day: 197, passage: "Lamentations 1-2", theme: "How lonely sits the city" },
  { day: 198, passage: "Lamentations 3-5", theme: "His mercies are new every morning" },
  { day: 199, passage: "Obadiah; Psalms 137", theme: "Edom's pride" },
  { day: 200, passage: "Ezekiel 1-4", theme: "Wheels, watchman" },
  { day: 201, passage: "Ezekiel 5-8", theme: "Idols in the temple" },
  { day: 202, passage: "Ezekiel 9-12", theme: "Glory departs" },
  { day: 203, passage: "Ezekiel 13-15", theme: "False prophets" },
  { day: 204, passage: "Ezekiel 16-17", theme: "Jerusalem's unfaithfulness" },
  { day: 205, passage: "Ezekiel 18-20", theme: "The soul that sins" },
  { day: 206, passage: "Ezekiel 21-23", theme: "Sword of the Lord" },
  { day: 207, passage: "Ezekiel 24-26", theme: "Tyre" },
  { day: 208, passage: "Ezekiel 27-29", theme: "Pharaoh" },
  { day: 209, passage: "Ezekiel 30-32", theme: "Against Egypt" },
  { day: 210, passage: "Ezekiel 33-36", theme: "I will give you a new heart" },
  { day: 211, passage: "Ezekiel 37-39", theme: "Valley of dry bones" },
  { day: 212, passage: "Ezekiel 40-42", theme: "Vision of the temple" },
  { day: 213, passage: "Ezekiel 43-45", theme: "Glory returns" },
  { day: 214, passage: "Ezekiel 46-48", theme: "The river, the city" },
  { day: 215, passage: "Daniel 1-3", theme: "Faithful in exile, fiery furnace" },
  { day: 216, passage: "Daniel 4-6", theme: "Nebuchadnezzar humbled, lions' den" },
  { day: 217, passage: "Daniel 7-9", theme: "Visions, seventy weeks" },
  { day: 218, passage: "Daniel 10-12", theme: "Final vision" },
  { day: 219, passage: "Ezra 1-3", theme: "Return" },
  { day: 220, passage: "Ezra 4-6; Haggai 1-2", theme: "Temple rebuilt" },
  { day: 221, passage: "Zechariah 1-7", theme: "Night visions" },
  { day: 222, passage: "Zechariah 8-14", theme: "King comes humble" },
  { day: 223, passage: "Esther 1-5", theme: "For such a time as this" },
  { day: 224, passage: "Esther 6-10", theme: "Reversal" },
  { day: 225, passage: "Ezra 7-10", theme: "Ezra's return, reforms" },
  { day: 226, passage: "Nehemiah 1-4", theme: "Walls rebuilt" },
  { day: 227, passage: "Nehemiah 5-7", theme: "Opposition, completed" },
  { day: 228, passage: "Nehemiah 8-10", theme: "Word read, covenant renewed" },
  { day: 229, passage: "Nehemiah 11-13", theme: "Repopulation" },
  { day: 230, passage: "Malachi 1-4", theme: "Sun of righteousness" },
  { day: 231, passage: "Psalms 78-83", theme: "Asaph" },
  { day: 232, passage: "Psalms 84-89", theme: "How lovely is your dwelling" },
  { day: 233, passage: "Psalms 90-97", theme: "Lord, you have been our dwelling" },
  { day: 234, passage: "Psalms 98-104", theme: "Bless the Lord, O my soul" },
  { day: 235, passage: "Psalms 105-107", theme: "Give thanks" },
  { day: 236, passage: "Psalms 108-114", theme: "Hallelu Yah" },
  { day: 237, passage: "Psalms 115-118", theme: "Not to us, O Lord" },
  { day: 238, passage: "Psalm 119", theme: "Your word is a lamp" },
  { day: 239, passage: "Psalms 120-131", theme: "Songs of ascent" },
  { day: 240, passage: "Psalms 132-138", theme: "Behold, how good" },
  { day: 241, passage: "Psalms 139-144", theme: "Search me, O God" },
  { day: 242, passage: "Psalms 145-150", theme: "Let everything that has breath" },
  { day: 243, passage: "Luke 1; John 1:1-14", theme: "The Word became flesh" },
  { day: 244, passage: "Matthew 1; Luke 2", theme: "Born in Bethlehem" },
  { day: 245, passage: "Matthew 2; Luke 2:39-52", theme: "Magi, boy in the temple" },
  { day: 246, passage: "Matthew 3; Mark 1; Luke 3", theme: "John the Baptist" },
  { day: 247, passage: "Matthew 4; Luke 4-5", theme: "Tempted, first disciples" },
  { day: 248, passage: "John 1:15-3:36", theme: "Behold the Lamb, born again" },
  { day: 249, passage: "John 4; Mark 2", theme: "Samaritan woman" },
  { day: 250, passage: "Matthew 5", theme: "Sermon on the Mount — Beatitudes" },
  { day: 251, passage: "Matthew 6-7", theme: "The Lord's Prayer" },
  { day: 252, passage: "Luke 6-7", theme: "Plain sermon, centurion" },
  { day: 253, passage: "Matthew 8-9; Mark 3-4", theme: "Healings, parables" },
  { day: 254, passage: "Matthew 10-11", theme: "Twelve sent out" },
  { day: 255, passage: "Matthew 12; Mark 5-6", theme: "Lord of the Sabbath" },
  { day: 256, passage: "Matthew 13; Luke 8", theme: "Kingdom parables" },
  { day: 257, passage: "Matthew 14-15; Mark 7-8", theme: "Feeding 5000, on the water" },
  { day: 258, passage: "Matthew 16-17; Mark 9", theme: "Confession, transfiguration" },
  { day: 259, passage: "Matthew 18; John 7-8", theme: "Forgive, light of the world" },
  { day: 260, passage: "John 9-10", theme: "Man born blind, Good Shepherd" },
  { day: 261, passage: "Luke 10-11", theme: "Mary and Martha" },
  { day: 262, passage: "Luke 12-13", theme: "Anxiety, the narrow door" },
  { day: 263, passage: "Luke 14-15", theme: "Lost sheep, coin, son" },
  { day: 264, passage: "Luke 16-17; John 11", theme: "Lazarus raised" },
  { day: 265, passage: "Luke 18; Matthew 19-20", theme: "Rich young ruler" },
  { day: 266, passage: "Matthew 21; Mark 11; Luke 19", theme: "Triumphal entry" },
  { day: 267, passage: "Matthew 22-23; Mark 12", theme: "Whose son is he?" },
  { day: 268, passage: "Matthew 24-25; Mark 13", theme: "Olivet discourse" },
  { day: 269, passage: "John 12-14", theme: "I am the way" },
  { day: 270, passage: "John 15-17", theme: "Vine, branches, high-priestly prayer" },
  { day: 271, passage: "Matthew 26; Mark 14; Luke 22", theme: "Last supper, Gethsemane" },
  { day: 272, passage: "Matthew 27; Mark 15; Luke 23; John 18-19", theme: "Crucified" },
  { day: 273, passage: "Matthew 28; Mark 16; Luke 24; John 20-21", theme: "He is risen" },
  { day: 274, passage: "Acts 1-3", theme: "Pentecost" },
  { day: 275, passage: "Acts 4-6", theme: "Bold witness" },
  { day: 276, passage: "Acts 7-8", theme: "Stephen, Philip" },
  { day: 277, passage: "Acts 9-10", theme: "Saul converted, Cornelius" },
  { day: 278, passage: "Acts 11-12", theme: "Antioch, Peter freed" },
  { day: 279, passage: "Acts 13-14", theme: "First missionary journey" },
  { day: 280, passage: "James 1-5", theme: "Faith without works" },
  { day: 281, passage: "Acts 15-16", theme: "Council, Philippi" },
  { day: 282, passage: "Galatians 1-3", theme: "Faith, not law" },
  { day: 283, passage: "Galatians 4-6", theme: "Free in Christ" },
  { day: 284, passage: "Acts 17-18; 1 Thessalonians 1-3", theme: "Thessalonica, Corinth" },
  { day: 285, passage: "1 Thessalonians 4-5; 2 Thessalonians 1-3", theme: "Coming of the Lord" },
  { day: 286, passage: "Acts 19; 1 Corinthians 1-4", theme: "Ephesus" },
  { day: 287, passage: "1 Corinthians 5-9", theme: "Holiness, freedom" },
  { day: 288, passage: "1 Corinthians 10-13", theme: "Love is patient" },
  { day: 289, passage: "1 Corinthians 14-16", theme: "Resurrection hope" },
  { day: 290, passage: "2 Corinthians 1-5", theme: "New creation" },
  { day: 291, passage: "2 Corinthians 6-9", theme: "Cheerful giver" },
  { day: 292, passage: "2 Corinthians 10-13", theme: "When I am weak" },
  { day: 293, passage: "Romans 1-3", theme: "All have sinned" },
  { day: 294, passage: "Romans 4-7", theme: "Justified by faith" },
  { day: 295, passage: "Romans 8-10", theme: "No condemnation" },
  { day: 296, passage: "Romans 11-13", theme: "Living sacrifice" },
  { day: 297, passage: "Romans 14-16", theme: "Welcome one another" },
  { day: 298, passage: "Acts 20-23", theme: "Paul arrested" },
  { day: 299, passage: "Acts 24-26", theme: "Before governors" },
  { day: 300, passage: "Acts 27-28", theme: "Shipwreck, Rome" },
  { day: 301, passage: "Colossians 1-4; Philemon", theme: "Christ preeminent" },
  { day: 302, passage: "Ephesians 1-3", theme: "Seated with Christ" },
  { day: 303, passage: "Ephesians 4-6", theme: "Armor of God" },
  { day: 304, passage: "Philippians 1-4", theme: "Rejoice always" },
  { day: 305, passage: "1 Timothy 1-6", theme: "Charge to Timothy" },
  { day: 306, passage: "Titus 1-3", theme: "Grace that trains" },
  { day: 307, passage: "1 Peter 1-5", theme: "Living hope" },
  { day: 308, passage: "Hebrews 1-4", theme: "Greater than" },
  { day: 309, passage: "Hebrews 5-7", theme: "Melchizedek" },
  { day: 310, passage: "Hebrews 8-10", theme: "Better covenant" },
  { day: 311, passage: "Hebrews 11-13", theme: "Cloud of witnesses" },
  { day: 312, passage: "2 Timothy 1-4", theme: "I have fought the good fight" },
  { day: 313, passage: "2 Peter 1-3; Jude", theme: "Contend for the faith" },
  { day: 314, passage: "1 John 1-5", theme: "God is love" },
  { day: 315, passage: "2 John; 3 John", theme: "Walking in truth" },
  { day: 316, passage: "Revelation 1-3", theme: "Letters to the seven" },
  { day: 317, passage: "Revelation 4-7", theme: "Throne room, the Lamb" },
  { day: 318, passage: "Revelation 8-11", theme: "Trumpets" },
  { day: 319, passage: "Revelation 12-14", theme: "Woman, dragon, harvest" },
  { day: 320, passage: "Revelation 15-18", theme: "Bowls, Babylon" },
  { day: 321, passage: "Revelation 19-22", theme: "He is coming" },
  { day: 322, passage: "1 Chronicles 1-3", theme: "Genealogies — remember" },
  { day: 323, passage: "1 Chronicles 4-6", theme: "Levites" },
  { day: 324, passage: "1 Chronicles 7-9", theme: "Tribes" },
  { day: 325, passage: "1 Chronicles 10-13", theme: "David made king" },
  { day: 326, passage: "1 Chronicles 14-16", theme: "Ark to Jerusalem" },
  { day: 327, passage: "1 Chronicles 17-20", theme: "Covenant restated" },
  { day: 328, passage: "1 Chronicles 21-23", theme: "Temple prep" },
  { day: 329, passage: "1 Chronicles 24-26", theme: "Priestly divisions" },
  { day: 330, passage: "1 Chronicles 27-29", theme: "David's final charge" },
  { day: 331, passage: "2 Chronicles 1-4", theme: "Temple built" },
  { day: 332, passage: "2 Chronicles 5-8", theme: "Glory fills the temple" },
  { day: 333, passage: "2 Chronicles 9-12", theme: "Solomon, Rehoboam" },
  { day: 334, passage: "2 Chronicles 13-16", theme: "Asa's reign" },
  { day: 335, passage: "2 Chronicles 17-20", theme: "Jehoshaphat" },
  { day: 336, passage: "2 Chronicles 21-25", theme: "Joash, Amaziah" },
  { day: 337, passage: "2 Chronicles 26-28", theme: "Uzziah, Ahaz" },
  { day: 338, passage: "2 Chronicles 29-32", theme: "Hezekiah revives worship" },
  { day: 339, passage: "2 Chronicles 33-36", theme: "Josiah, exile, decree" },
  { day: 340, passage: "Re-read: Genesis 1-3; Psalm 1", theme: "Begin again — the source" },
  { day: 341, passage: "Re-read: Matthew 5-7", theme: "The Sermon" },
  { day: 342, passage: "Re-read: John 14-17", theme: "His final words" },
  { day: 343, passage: "Re-read: Romans 8", theme: "No condemnation" },
  { day: 344, passage: "Re-read: 1 Corinthians 13", theme: "Love" },
  { day: 345, passage: "Re-read: Ephesians 1-3", theme: "In Christ" },
  { day: 346, passage: "Re-read: Philippians 4", theme: "Rejoice" },
  { day: 347, passage: "Re-read: Hebrews 11-12", theme: "Faith" },
  { day: 348, passage: "Re-read: James 1", theme: "Doer of the word" },
  { day: 349, passage: "Re-read: 1 John 4", theme: "God is love" },
  { day: 350, passage: "Re-read: Revelation 21-22", theme: "All things new" },
  { day: 351, passage: "Reflect: highlight three passages from this year", theme: "Recall" },
  { day: 352, passage: "Reflect: what has God taught me?", theme: "Examen" },
  { day: 353, passage: "Reflect: my five most-treasured verses", theme: "Hide in your heart" },
  { day: 354, passage: "Memorise: Psalm 23", theme: "The Lord is my shepherd" },
  { day: 355, passage: "Memorise: Romans 12:1-2", theme: "Living sacrifice" },
  { day: 356, passage: "Memorise: Galatians 5:22-23", theme: "Fruit of the Spirit" },
  { day: 357, passage: "Memorise: Philippians 4:6-8", theme: "Think on these" },
  { day: 358, passage: "Memorise: 1 Corinthians 13:4-7", theme: "Love is" },
  { day: 359, passage: "Memorise: Hebrews 12:1-2", theme: "Fix your eyes" },
  { day: 360, passage: "Memorise: Isaiah 53", theme: "The suffering servant" },
  { day: 361, passage: "Pray through Psalm 51", theme: "Create in me" },
  { day: 362, passage: "Pray through Psalm 139", theme: "Search me" },
  { day: 363, passage: "Pray through John 17", theme: "His prayer for us" },
  { day: 364, passage: "Pray Ephesians 3:14-21 over your life", theme: "Rooted in love" },
  { day: 365, passage: "Pray Revelation 22:17-21", theme: "Come, Lord Jesus" },
];

export function planFor(day: number): PlanDay {
  const clamped = Math.max(1, Math.min(365, day));
  return CHRONO_PLAN[clamped - 1];
}

// Resolve the active plan entry for a day, applying any user override
// from Settings → planOverrides. The override is just a passage string;
// the theme stays from the canonical plan so the user keeps the context.
export function planForWithOverride(
  day: number,
  overrides: Record<number, string> | undefined,
): PlanDay {
  const base = planFor(day);
  const override = overrides?.[day];
  if (override && override.trim()) return { ...base, passage: override.trim() };
  return base;
}

// Convert calendar date → plan day, using the user's start anchor.
// startDate is a date string when they were on startPlanDay.
export function planDayFor(
  iso: string,
  startDate: string,
  startPlanDay: number,
): number {
  const [ay, am, ad] = iso.split("-").map(Number);
  const [by, bm, bd] = startDate.split("-").map(Number);
  const diff = Math.round(
    (Date.UTC(ay, am - 1, ad) - Date.UTC(by, bm - 1, bd)) / 86_400_000,
  );
  let d = startPlanDay + diff;
  while (d < 1) d += 365;
  while (d > 365) d -= 365;
  return d;
}
